<?php

namespace Database\Seeders;

use App\Models\Admin\Asset\AssetListModel;
use Illuminate\Database\Seeder;

class AssetListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $adminAssetList = [
            ['id' => '1', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/line_staff/DIyQ3CuEBiYa2Ql7zARFylYHbSEIhQmL2pan9QAL.mp4', 'keyword' => 'LINE STAFF - HOW TO DECLARE SUBSTANDARD ITEMS', 'file_path' => 'public/assets/mos/video_tutorials/line_staff', 'original_file_name' => 'LINE STAFF - HOW TO DECLARE SUBSTANDARD ITEMS.mp4', 'altered_file_name' => 'DIyQ3CuEBiYa2Ql7zARFylYHbSEIhQmL2pan9QAL.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 07:49:00', 'updated_at' => '2024-08-12 07:49:00'],
            ['id' => '2', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/line_staff/Z7qUZK2ZGyabshPXWrSVoquw5N23wBtYCLnGQfHr.mp4', 'keyword' => 'LINE STAFF - HOW TO TRANSFER SCANNED ITEMS TO WAREHOUSE', 'file_path' => 'public/assets/mos/video_tutorials/line_staff', 'original_file_name' => 'LINE STAFF - HOW TO TRANSFER SCANNED ITEMS TO WAREHOUSE.mp4', 'altered_file_name' => 'Z7qUZK2ZGyabshPXWrSVoquw5N23wBtYCLnGQfHr.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 07:50:01', 'updated_at' => '2024-08-12 07:50:01'],
            ['id' => '3', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/line_staff/7LrN2Fo06OdAzIWmQnyx6otm5OeI3QruWfCqnx2U.mp4', 'keyword' => 'LINE STAFF - HOW TO TRANSFER THE PAHABOL ITEMS', 'file_path' => 'public/assets/mos/video_tutorials/line_staff', 'original_file_name' => 'LINE STAFF - HOW TO TRANSFER THE PAHABOL ITEMS.mp4', 'altered_file_name' => '7LrN2Fo06OdAzIWmQnyx6otm5OeI3QruWfCqnx2U.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 07:50:23', 'updated_at' => '2024-08-12 07:50:23'],
            ['id' => '4', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/quality_assurance/XVNWRNmpHAMESNFRBMr4ERvZAQ573VgrCdP6vvxJ.mp4', 'keyword' => 'QA - HOW TO TAG FOR DISPOSITION OF ITEMS', 'file_path' => 'public/assets/mos/video_tutorials/quality_assurance', 'original_file_name' => 'QA - HOW TO TAG FOR DISPOSITION OF ITEMS.mp4', 'altered_file_name' => 'XVNWRNmpHAMESNFRBMr4ERvZAQ573VgrCdP6vvxJ.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 07:52:06', 'updated_at' => '2024-08-12 07:52:06'],
            ['id' => '5', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/quality_assurance/V1i4s4bU3Ue656zvTNcIH99Hx0v7YnZhUrstROQs.mp4', 'keyword' => 'QA - HOW TO TAG ITEMS AS FOR INVESTIGATION', 'file_path' => 'public/assets/mos/video_tutorials/quality_assurance', 'original_file_name' => 'QA - HOW TO TAG ITEMS AS FOR INVESTIGATION.mp4', 'altered_file_name' => 'V1i4s4bU3Ue656zvTNcIH99Hx0v7YnZhUrstROQs.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 07:53:51', 'updated_at' => '2024-08-12 07:53:51'],
            ['id' => '6', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/quality_assurance/8D0k9Ul7dq7Ra2nc2ZvLRjONDr1D1jxhFtF82iDi.mp4', 'keyword' => 'QA - HOW TO TAG ITEMS AS FOR SAMPLING', 'file_path' => 'public/assets/mos/video_tutorials/quality_assurance', 'original_file_name' => 'QA - HOW TO TAG ITEMS AS FOR SAMPLING.mp4', 'altered_file_name' => '8D0k9Ul7dq7Ra2nc2ZvLRjONDr1D1jxhFtF82iDi.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 07:54:14', 'updated_at' => '2024-08-12 07:54:14'],
            ['id' => '7', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/quality_assurance/axkOaTf7X7SWsFEVZDonMKQOxFTMIgghZie9m9wC.mp4', 'keyword' => 'QA - TAGGING OF ITEMS ON HOLD AND FOR RELEASE', 'file_path' => 'public/assets/mos/video_tutorials/quality_assurance', 'original_file_name' => 'QA - TAGGING OF ITEMS ON HOLD AND FOR RELEASE.mp4', 'altered_file_name' => 'axkOaTf7X7SWsFEVZDonMKQOxFTMIgghZie9m9wC.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 07:54:31', 'updated_at' => '2024-08-12 07:54:31'],
            ['id' => '8', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/supply_planner/eIT2Jr5cchnUzjbLZSo2hpZZ3yMwzcAamQ9CYBP9.mp4', 'keyword' => 'PPIC  - HOW TO IMPORT ORDERS', 'file_path' => 'public/assets/mos/video_tutorials/supply_planner', 'original_file_name' => 'PPIC  - HOW TO IMPORT ORDERS.mp4', 'altered_file_name' => 'eIT2Jr5cchnUzjbLZSo2hpZZ3yMwzcAamQ9CYBP9.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:19:31', 'updated_at' => '2024-08-12 23:19:31'],
            ['id' => '9', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/supply_planner/BgarxQgJMAvLTNUeF9PnCxL8qfjLStiXIlRRjmAJ.mp4', 'keyword' => 'PPIC - HOW TO BACKTRACK THE ORDERS', 'file_path' => 'public/assets/mos/video_tutorials/supply_planner', 'original_file_name' => 'PPIC - HOW TO BACKTRACK THE ORDERS.mp4', 'altered_file_name' => 'BgarxQgJMAvLTNUeF9PnCxL8qfjLStiXIlRRjmAJ.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:19:47', 'updated_at' => '2024-08-12 23:19:47'],
            ['id' => '10', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/supply_planner/fjKJdYgCCCIIOz8qVLHTpsYMJlSO2NiFYoJhHZ4c.mp4', 'keyword' => 'PPIC - HOW TO FILTER, SORT & SEARCH', 'file_path' => 'public/assets/mos/video_tutorials/supply_planner', 'original_file_name' => 'PPIC - HOW TO FILTER, SORT & SEARCH.mp4', 'altered_file_name' => 'fjKJdYgCCCIIOz8qVLHTpsYMJlSO2NiFYoJhHZ4c.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:20:03', 'updated_at' => '2024-08-12 23:20:03'],
            ['id' => '11', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/supply_planner/BYzIYPSzMPQ3O3tbN7lT7YnxNfL1gMRjSTLjjLhE.mp4', 'keyword' => 'PPIC - HOW TO MONITOR THE PRODUCTION ORDER', 'file_path' => 'public/assets/mos/video_tutorials/supply_planner', 'original_file_name' => 'PPIC - HOW TO MONITOR THE PRODUCTION ORDER.mp4', 'altered_file_name' => 'BYzIYPSzMPQ3O3tbN7lT7YnxNfL1gMRjSTLjjLhE.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:20:12', 'updated_at' => '2024-08-12 23:20:12'],
            ['id' => '12', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/supply_planner/Km6RysQOioVT4kgdn62wuTx5JnTIwCZBQOgJeXqV.mp4', 'keyword' => 'PPIC - REOPEN AND TAG ORDER AS COMPLETED', 'file_path' => 'public/assets/mos/video_tutorials/supply_planner', 'original_file_name' => 'PPIC - REOPEN AND TAG ORDER AS COMPLETED.mp4', 'altered_file_name' => 'Km6RysQOioVT4kgdn62wuTx5JnTIwCZBQOgJeXqV.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:20:24', 'updated_at' => '2024-08-12 23:20:24'],
            ['id' => '13', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/team_leader/kCdk2HaVDbQavmnyIhcVRE0fglLxQZgvmJQXrWlH.mp4', 'keyword' => 'TL - HOW TO ADD ADDITIONAL STICKER QUANTITY', 'file_path' => 'public/assets/mos/video_tutorials/team_leader', 'original_file_name' => 'TL - HOW TO ADD ADDITIONAL STICKER QUANTITY.mp4', 'altered_file_name' => 'kCdk2HaVDbQavmnyIhcVRE0fglLxQZgvmJQXrWlH.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:21:26', 'updated_at' => '2024-08-12 23:21:26'],
            ['id' => '14', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/team_leader/5xnWP1gWS2d9X6Ngjx5hggFZTnKaRBlC9gT1DAPn.mp4', 'keyword' => 'TL - HOW TO DEACTIVATE STICKER', 'file_path' => 'public/assets/mos/video_tutorials/team_leader', 'original_file_name' => 'TL - HOW TO DEACTIVATE STICKER.mp4', 'altered_file_name' => '5xnWP1gWS2d9X6Ngjx5hggFZTnKaRBlC9gT1DAPn.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:21:33', 'updated_at' => '2024-08-12 23:21:33'],
            ['id' => '15', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/team_leader/Pc9vc49qW0hxZfpLZO5dZrwt5IoJpipAkg1YQOQN.mp4', 'keyword' => 'TL - HOW TO PROCESS ITEMS ENDORSED BY QA', 'file_path' => 'public/assets/mos/video_tutorials/team_leader', 'original_file_name' => 'TL - HOW TO PROCESS ITEMS ENDORSED BY QA.mp4', 'altered_file_name' => 'Pc9vc49qW0hxZfpLZO5dZrwt5IoJpipAkg1YQOQN.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:21:40', 'updated_at' => '2024-08-12 23:21:40'],
            ['id' => '16', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/team_leader/MV9dP5jmmJaHPVvRGMoiwVNkxVsMVK4eQBNdMB7D.mp4', 'keyword' => 'TL - HOW TO REPRINT BATCH STICKERS', 'file_path' => 'public/assets/mos/video_tutorials/team_leader', 'original_file_name' => 'TL - HOW TO REPRINT BATCH STICKERS.mp4', 'altered_file_name' => 'MV9dP5jmmJaHPVvRGMoiwVNkxVsMVK4eQBNdMB7D.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:21:48', 'updated_at' => '2024-08-12 23:21:48'],
            ['id' => '17', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/team_leader/NhJEDf9UbG2PvAm40l6Oy1N8CVyCoUXiMy4MggZw.mp4', 'keyword' => 'TL -HOW TO CREATE AND PRINT BATCH STICKERS', 'file_path' => 'public/assets/mos/video_tutorials/team_leader', 'original_file_name' => 'TL -HOW TO CREATE AND PRINT BATCH STICKERS.mp4', 'altered_file_name' => 'NhJEDf9UbG2PvAm40l6Oy1N8CVyCoUXiMy4MggZw.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:21:55', 'updated_at' => '2024-08-12 23:21:55'],
            ['id' => '18', 'file' => 'https://mos-api.onemarygrace.com/storage/assets/mos/video_tutorials/warehouse/wOH25uS20Q3MxbiwkCTInbF7vLj5KXvCGo50BxT2.mp4', 'keyword' => 'WAREHOUSE - HOW TO RECEIVE THE ITEMS', 'file_path' => 'public/assets/mos/video_tutorials/warehouse', 'original_file_name' => 'WAREHOUSE - HOW TO RECEIVE THE ITEMS.mp4', 'altered_file_name' => 'wOH25uS20Q3MxbiwkCTInbF7vLj5KXvCGo50BxT2.mp4', 'created_by_id' => '0000', 'created_at' => '2024-08-12 23:22:43', 'updated_at' => '2024-08-12 23:22:43']
        ];

        foreach ($adminAssetList as $value) {
            AssetListModel::create([
                'created_by_id' => '0000',
                'file' => $value['file'],
                'keyword' => $value['keyword'],
                'file_path' => $value['file_path'],
                'original_file_name' => $value['original_file_name'],
                'altered_file_name' => $value['altered_file_name'],
            ]);
        }
    }
}
