<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Settings\Items\ItemMasterdataModel;

class ItemMasterdataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $createdById = 1;
        $itemMasterdata = [
            [
                "item_code" => "CR 12",
                "description" => "Cheese rolls box of 12",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 6,
                "storage_type_id" => 1,
                "uom_id" => 3,
                "primary_item_packing_size" => 12,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CR 6",
                "description" => "Cheese rolls box of 6",
                "parent_id" => "CR 12",
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 7,
                "storage_type_id" => 1,
                "uom_id" => 3,
                "primary_item_packing_size" => 6,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "EQ 12",
                "description" => "Ensaymada box of 12",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 6,
                "storage_type_id" => 1,
                "uom_id" => 3,
                "primary_item_packing_size" => 12,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => 30
            ],
            [
                "item_code" => "EQ 6",
                "description" => "Ensaymada box of 6",
                "parent_id" => "EQ 12",
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 7,
                "storage_type_id" => 1,
                "uom_id" => 3,
                "primary_item_packing_size" => 6,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => 30
            ],
            [
                "item_code" => "MM 12",
                "description" => "Mamon Box of 12",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 6,
                "storage_type_id" => 1,
                "uom_id" => 3,
                "primary_item_packing_size" => 12,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "MM 6",
                "description" => "Mamon box of 6",
                "parent_id" => "MM 12",
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 7,
                "storage_type_id" => 1,
                "uom_id" => 3,
                "primary_item_packing_size" => 6,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CR PCS",
                "description" => "Cheese rolls piece",
                "parent_id" => "CR 12",
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 8,
                "storage_type_id" => 1,
                "uom_id" => 1,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 1,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "EQ PCS",
                "description" => "QDB Ensaymada piece",
                "parent_id" => "EQ 12",
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 8,
                "storage_type_id" => 1,
                "uom_id" => 1,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 1,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => 30
            ],
            [
                "item_code" => "MM PCS",
                "description" => "Mary Grace Mamon piece",
                "parent_id" => "MM 12",
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 8,
                "storage_type_id" => 1,
                "uom_id" => 1,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 1,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "EQ MN",
                "description" => "Ensaymada Mini",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 8,
                "storage_type_id" => 1,
                "uom_id" => 1,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 1,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => 30
            ],
            [
                "item_code" => "MEQ 12",
                "description" => "Manchego Ensaymada Box of 12",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 6,
                "storage_type_id" => 1,
                "uom_id" => 3,
                "primary_item_packing_size" => 12,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CR FZ PCS",
                "description" => "Cheeseroll Frozen - Hubad",
                "parent_id" => "CR 12",
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 8,
                "storage_type_id" => 1,
                "uom_id" => 1,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 1,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "EQ FZ PCS",
                "description" => "Ensaymada - Frozen Hubad",
                "parent_id" => "EQ 12",
                "item_classification_id" => 1,
                "item_category_id" => 1,
                "item_variant_type_id" => 8,
                "storage_type_id" => 1,
                "uom_id" => 1,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 1,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => 1,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "PD",
                "description" => "Pudding",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 4,
                "item_variant_type_id" => 10,
                "storage_type_id" => 1,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 15,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CTI WH",
                "description" => "Chocolate Rum Tiramisu Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CTI MN",
                "description" => "Chocolate Rum Tiramisu Mini",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 2,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 7,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CTI SL",
                "description" => "Chocolate Rum Tiramisu Slice",
                "parent_id" => "CTI WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CH WH",
                "description" => "Chocolate Cake Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 15,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CH MN",
                "description" => "Chocolate Cake Mini",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 2,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 15,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CH SL",
                "description" => "Chocolate Cake Slice",
                "parent_id" => "CH WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "VT WH",
                "description" => "Velvet Cake Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 12,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "VT MN",
                "description" => "Velvet Cake Mini",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 2,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 12,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "VT SL",
                "description" => "Velvet Cake Slice",
                "parent_id" => "VT WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "TR WH",
                "description" => "Chocolate Truffle Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 16,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "TR MN",
                "description" => "Chocolate Truffle Mini",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 2,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 16,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "TR SL",
                "description" => "Chocolate Truffle Slice",
                "parent_id" => "TR WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CM WH",
                "description" => "Chocolate Mousse Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 3,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => 11
            ],
            [
                "item_code" => "CM MN",
                "description" => "Chocolate Mousse Mini",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 2,
                "storage_type_id" => 3,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => 11
            ],
            [
                "item_code" => "CM SL",
                "description" => "Chocolate Mousse Slice",
                "parent_id" => "CM WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "SW WH",
                "description" => "Strawberry Short Cake Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 6,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "SW SL",
                "description" => "Strawberry Short Cake Slice",
                "parent_id" => "SW WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "SSCV WH",
                "description" => "Sea Salt Caramel Vanilla Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 9,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "SSCV MN",
                "description" => "Sea Salt Caramel Vanilla Mini",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 2,
                "storage_type_id" => 2,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 9,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "SSCV SL",
                "description" => "Sea Salt Caramel Vanilla Slice",
                "parent_id" => "SSCV WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CC WH",
                "description" => "Cheesecake Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 3,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 10,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CC MN",
                "description" => "Cheesecake Mini",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 2,
                "storage_type_id" => 3,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => 10,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "CC SL",
                "description" => "Cheesecake Slice",
                "parent_id" => "CC WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "LI  WH",
                "description" => "Limone Santi Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 3,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => 15
            ],
            [
                "item_code" => "LI SL",
                "description" => "Limone Santi Slice",
                "parent_id" => "LI  WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ],
            [
                "item_code" => "BA WH",
                "description" => "Banana Bella Whole",
                "parent_id" => null,
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 1,
                "storage_type_id" => 3,
                "uom_id" => 3,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 2,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => 12
            ],
            [
                "item_code" => "BA SL",
                "description" => "Banana Bella Slice",
                "parent_id" => "BA WH",
                "item_classification_id" => 1,
                "item_category_id" => 2,
                "item_variant_type_id" => 3,
                "storage_type_id" => 2,
                "uom_id" => 5,
                "primary_item_packing_size" => 1,
                "primary_conversion_id" => 3,
                "secondary_item_packing_size" => null,
                "secondary_conversion_id" => null,
                "plant_id" => 2,
                "ambient_shelf_life" => null,
                "chilled_shelf_life" => null,
                "frozen_shelf_life" => null
            ]
        ];


        foreach ($itemMasterdata as $value) {
            ItemMasterdataModel::create([
                'created_by_id' => $createdById,
                'description' => $value['description'],
                'item_code' => $value['item_code'],
                'item_classification_id' => $value['item_classification_id'],
                'item_category_id' => $value['item_category_id'],
                'storage_type_id' => $value['storage_type_id'],
                'item_variant_type_id' => $value['item_variant_type_id'],
                'plant_id' => $value['plant_id'],
                'parent_item_id' => $this->onGetParentId($value['parent_id']),
                'ambient_shelf_life' => $value['ambient_shelf_life'],
                'chilled_shelf_life' => $value['chilled_shelf_life'],
                'frozen_shelf_life' => $value['frozen_shelf_life'],
                'uom_id' => $value['uom_id'],
                'primary_item_packing_size' => $value['primary_item_packing_size'],
                'secondary_item_packing_size' => $value['secondary_item_packing_size'],
                'primary_conversion_id' => $value['primary_conversion_id'],
                'secondary_conversion_id' => $value['secondary_conversion_id'],
            ]);
        }
    }

    public function onGetParentId($value)
    {
        $item = ItemMasterdataModel::where('item_code', $value)->first();
        return $item->id ?? null;
    }
}
