<?php

namespace Database\Seeders\WmsSeeder;

use App\Models\WMS\Settings\ItemMasterData\ItemCategoryModel;
use App\Models\WMS\Settings\ItemMasterData\ItemClassificationModel;
use App\Models\WMS\Settings\ItemMasterData\ItemConversionModel;
use App\Models\WMS\Settings\ItemMasterData\ItemUomModel;
use App\Models\WMS\Settings\ItemMasterData\ItemVariantTypeModel;
use App\Models\WMS\Settings\StorageMasterData\FacilityPlantModel;
use App\Models\WMS\Settings\StorageMasterData\StorageTypeModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\WMS\Settings\ItemMasterData\ItemMasterdataModel;

class ItemMasterdataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $createdById = 1;
        $itemMasterdata =
            [
                [
                    "item_code" => "CR 12",
                    "description" => "Cheese rolls box of 12",
                    "item_short_name" => "Cheese rolls 12",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-BO12",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 12,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CR 6",
                    "description" => "Cheese rolls box of 6",
                    "item_short_name" => "Cheese rolls 6",
                    "parent_code" => "CR 12",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-BO6",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 6,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "EQ 12",
                    "description" => "Ensaymada box of 12",
                    "item_short_name" => "Ensay 12",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-BO12",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 12,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => 30,
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "EQ 6",
                    "description" => "Ensaymada box of 6",
                    "item_short_name" => "Ensay 6",
                    "parent_code" => "EQ 12",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-BO6",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 6,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => 30,
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "MM 12",
                    "description" => "Mamon Box of 12",
                    "item_short_name" => "Mamon 12",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-BO12",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 12,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "MM 6",
                    "description" => "Mamon box of 6",
                    "item_short_name" => "Mamon 6",
                    "parent_code" => "MM 12",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-BO6",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 6,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CR PCS",
                    "description" => "Cheese rolls piece",
                    "item_short_name" => "Chesse rolls PCS",
                    "parent_code" => "CR 12",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-PIE",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-PCS",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "EQ PCS",
                    "description" => "QDB Ensaymada piece",
                    "item_short_name" => "QDB Ensaymada PCS",
                    "parent_code" => "EQ 12",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-PIE",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-PCS",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => 30,
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "MM PCS",
                    "description" => "Mary Grace Mamon piece",
                    "item_short_name" => "Mary Grace PCS",
                    "parent_code" => "MM 12",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-PIE",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-PCS",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "EQ MN",
                    "description" => "Ensaymada Mini",
                    "item_short_name" => "Ensay MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-PIE",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-PCS",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => 30,
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "MEQ 12",
                    "description" => "Manchego Ensaymada Box of 12",
                    "item_short_name" => "Manchego Ensay 12",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-BO12",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 12,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CR FZ PCS",
                    "description" => "Cheeseroll Frozen - Hubad",
                    "item_short_name" => "Cheeseroll FZ PCS",
                    "parent_code" => "CR 12",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-PIE",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-PCS",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "EQ FZ PCS",
                    "description" => "Ensaymada - Frozen Hubad",
                    "item_short_name" => "Ensaymada - FZ PCS",
                    "parent_code" => "EQ 12",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-BRE",
                    "item_variant_type_code" => "VRNT-PIE",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-PCS",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 1,
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "PD",
                    "description" => "Pudding",
                    "item_short_name" => "Pudding",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-LOA",
                    "item_variant_type_code" => "VRNT-LOA",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "is_viewable_by_otb" => 1,
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 15,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CTI WH",
                    "description" => "Chocolate Rum Tiramisu Whole",
                    "item_short_name" => "Choco Rum WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CTI MN",
                    "description" => "Chocolate Rum Tiramisu Mini",
                    "item_short_name" => "Choco Rum MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 7,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CTI SL",
                    "description" => "Chocolate Rum Tiramisu Slice",
                    "item_short_name" => "Choco Rum SL",
                    "parent_code" => "CTI WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 2,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CH WH",
                    "description" => "Chocolate Cake Whole",
                    "item_short_name" => "Choco WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 15,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CH MN",
                    "description" => "Chocolate Cake Mini",
                    "item_short_name" => "Choco MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 15,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CH SL",
                    "description" => "Chocolate Cake Slice",
                    "item_short_name" => "Choco SL",
                    "parent_code" => "CH WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 2,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "VT WH",
                    "description" => "Velvet Cake Whole",
                    "item_short_name" => "Velvet Cake WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 12,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "VT MN",
                    "description" => "Velvet Cake Mini",
                    "item_short_name" => "Velvet Cake MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 12,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "VT SL",
                    "description" => "Velvet Cake Slice",
                    "item_short_name" => "Velvet Cake SL",
                    "parent_code" => "VT WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 2,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "TR WH",
                    "description" => "Chocolate Truffle Whole",
                    "item_short_name" => "Truffle WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 16,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "TR MN",
                    "description" => "Chocolate Truffle Mini",
                    "item_short_name" => "Truffle MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 16,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "TR SL",
                    "description" => "Chocolate Truffle Slice",
                    "item_short_name" => "Truffle SL",
                    "parent_code" => "TR WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 2,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CM WH",
                    "description" => "Chocolate Mousse Whole",
                    "item_short_name" => "Choco Mousse WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 11,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "CM MN",
                    "description" => "Chocolate Mousse Mini",
                    "item_short_name" => "Choco Mousse MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 11,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "CM SL",
                    "description" => "Chocolate Mousse Slice",
                    "item_short_name" => "Choco Mousse SL",
                    "parent_code" => "CM WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 2,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "SW WH",
                    "description" => "Strawberry Short Cake Whole",
                    "item_short_name" => "Straw Cake WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-PIE",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 6,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "SW SL",
                    "description" => "Strawberry Short Cake Slice",
                    "item_short_name" => "Straw Cake SL",
                    "parent_code" => "SW WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 2,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "SSCV WH",
                    "description" => "Sea Salt Caramel Vanilla Whole",
                    "item_short_name" => "Sea Salt WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 9,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "SSCV MN",
                    "description" => "Sea Salt Caramel Vanilla Mini",
                    "item_short_name" => "Sea Salt MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 9,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "SSCV SL",
                    "description" => "Sea Salt Caramel Vanilla Slice",
                    "item_short_name" => "Sea Salt SL",
                    "parent_code" => "SSCV WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 2,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CC WH",
                    "description" => "Cheesecake Whole",
                    "item_short_name" => "Cheese Cake WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 10,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CC MN",
                    "description" => "Cheesecake Mini",
                    "item_short_name" => "Cheese Cake MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 10,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CC SL",
                    "description" => "Cheesecake Slice",
                    "item_short_name" => "Cheese Cake SL",
                    "parent_code" => "CC WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 2,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "LI  WH",
                    "description" => "Limone Santi Whole",
                    "item_short_name" => "Limone WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 15,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "LI SL",
                    "description" => "Limone Santi Slice",
                    "item_short_name" => "Limone SL",
                    "parent_code" => "LI  WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 2,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "BA WH",
                    "description" => "Banana Bella Whole",
                    "item_short_name" => "Banana Bella WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 12,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "BA SL",
                    "description" => "Banana Bella Slice",
                    "item_short_name" => "Banana Bella SL",
                    "parent_code" => "BA WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 2,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "MB WH",
                    "description" => "Mango Bene Whole",
                    "item_short_name" => "Mango Bene WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 12,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "MB SL",
                    "description" => "Mango Bene Slice",
                    "item_short_name" => "Mango Bene SL",
                    "parent_code" => "MB WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 2,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "TAS WH",
                    "description" => "Toasted Almond Sansrival Whole",
                    "item_short_name" => "Sansi WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 16,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "TAS MN",
                    "description" => "Toasted Almond Sansrival Mini",
                    "item_short_name" => "Sansi MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 16,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "TAS SL",
                    "description" => "Toasted Almond Sansrival Slice",
                    "item_short_name" => "Sansi SL",
                    "parent_code" => "TAS WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-FRO",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => 2,
                    "sticker_remarks_code" => "STIC-KEEP-FROZEN"
                ],
                [
                    "item_code" => "CK WH",
                    "description" => "Carrot Cake",
                    "item_short_name" => "Carrot Cake WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 12,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "CK SL",
                    "description" => "Carrot Cake Slice",
                    "item_short_name" => "Carrot Cake SL",
                    "parent_code" => "CK WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-CLM",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 2,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "FC LF",
                    "description" => "Fruit Cake Loaf",
                    "item_short_name" => "Fruit Cake LF",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-LOA",
                    "item_variant_type_code" => "VRNT-LOA",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "is_viewable_by_otb" => 1,
                    "ambient_shelf_life" => 365,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED-OPN"
                ],
                [
                    "item_code" => "FC SL",
                    "description" => "Fruit Cake Slice",
                    "item_short_name" => "Fruit Cake SL",
                    "parent_code" => "FC LF",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-LOA",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-PCS",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "is_viewable_by_otb" => 1,
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 90,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED-OPN"
                ],
                [
                    "item_code" => "TRC MN",
                    "description" => "Truffle Rose 2024",
                    "item_short_name" => "Truffle Rose MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 16,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "BR 8",
                    "description" => "Brownies 8s",
                    "item_short_name" => "Brownies 8",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-BO8",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 8,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 12,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED-OPN"
                ],
                [
                    "item_code" => "BR 4",
                    "description" => "Brownies 4s",
                    "item_short_name" => "Brownies 4",
                    "parent_code" => "BR 8",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-BO4",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 4,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 12,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED-OPN"
                ],
                [
                    "item_code" => "FFG 8",
                    "description" => "Food for the Gods 8s",
                    "item_short_name" => "Food For Gods 8",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-BO8",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 8,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 10,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED-OPN"
                ],
                [
                    "item_code" => "FFG 4",
                    "description" => "Food for the Gods 4s",
                    "item_short_name" => "Food For Gods 4",
                    "parent_code" => "FFG 8",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-BO4",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 4,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 10,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED-OPN"
                ],
                [
                    "item_code" => "LMS 8",
                    "description" => "Lemon Bars 8s",
                    "item_short_name" => "Lemon Bars 8",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-BO8",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 8,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 12,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED-OPN"
                ],
                [
                    "item_code" => "LMS 4",
                    "description" => "Lemon Bars 4s",
                    "item_short_name" => "Lemon Bars 4",
                    "parent_code" => "LMS 8",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-BO4",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => 4,
                    "primary_conversion_code" => "CON-PCS",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 12,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED-OPN"
                ],
                [
                    "item_code" => "BD LF",
                    "description" => "Banana Bread",
                    "item_short_name" => "Banana Bread",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-LOA",
                    "item_variant_type_code" => "VRNT-LOA",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 10,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "AP WH",
                    "description" => "Apple Pie Whole",
                    "item_short_name" => "Apple Pie WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 12,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "AP MN",
                    "description" => "Apple Pie Mini",
                    "item_short_name" => "Apple Pie MN",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-MIN",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 12,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "LGB",
                    "description" => "Butter Lengua",
                    "item_short_name" => "Butter Lengua",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-JAR",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 30,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-COVERED-AMB"
                ],
                [
                    "item_code" => "LGDC",
                    "description" => "Dark Chocolate Lengua",
                    "item_short_name" => "Dark Choco Lengua",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-JAR",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 30,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-COVERED-AMB"
                ],
                [
                    "item_code" => "LGQB",
                    "description" => "Queso de Bola Lengua",
                    "item_short_name" => "Queso Lengua",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-JAR",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 30,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-COVERED-AMB"
                ],
                [
                    "item_code" => "LGRC",
                    "description" => "Ruby Belgian Chocolate Lengua Thins",
                    "item_short_name" => "Ruby Lengua",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-PAS",
                    "item_variant_type_code" => "VRNT-JAR",
                    "storage_type_code" => "ST-AMB",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => 30,
                    "chilled_shelf_life" => "",
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-COVERED-AMB"
                ],
                [
                    "item_code" => "TLC WH",
                    "description" => "Tres Leches Cake Whole",
                    "item_short_name" => "Tres Leches WH",
                    "parent_code" => "",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-WHO",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-BOX",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 10,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ],
                [
                    "item_code" => "TLC SL",
                    "description" => "Tres Leches Cake Slice",
                    "item_short_name" => "Tres Leches SL",
                    "parent_code" => "TLC WH",
                    "item_classification_code" => "CLS-FG",
                    "item_category_code" => "CAT-CAK",
                    "item_variant_type_code" => "VRNT-SLI",
                    "storage_type_code" => "ST-CHI",
                    "uom_code" => "UOM-POB",
                    "primary_item_packing_size" => "",
                    "primary_conversion_code" => "",
                    "secondary_item_packing_size" => "",
                    "secondary_conversion_code" => "",
                    "plant_code" => "02",
                    "ambient_shelf_life" => "",
                    "chilled_shelf_life" => 2,
                    "frozen_shelf_life" => "",
                    "sticker_remarks_code" => "STIC-KEEP-CHILLED"
                ]
            ];


        foreach ($itemMasterdata as $value) {
            ItemMasterdataModel::create([
                'created_by_id' => $createdById,
                'description' => $value['description'],
                'short_name' => $value['item_short_name'],
                'item_code' => $value['item_code'],
                'item_classification_id' => $this->onGetItemCategory($value['item_classification_code']),
                'item_category_id' => $this->onGetItemCategory($value['item_category_code']),
                'storage_type_id' => $this->onGetStorageType($value['storage_type_code']),
                'item_variant_type_id' => $this->onGetItemVariantType($value['item_variant_type_code']),
                'plant_id' => $this->onGetPlant($value['plant_code']),
                'parent_item_id' => $this->onGetParentId($value['parent_code']),
                'ambient_shelf_life' => $value['ambient_shelf_life'] == "" ? null : $value['ambient_shelf_life'],
                'chilled_shelf_life' => $value['chilled_shelf_life'] == "" ? null : $value['chilled_shelf_life'],
                'frozen_shelf_life' => $value['frozen_shelf_life'] == "" ? null : $value['frozen_shelf_life'],
                'uom_id' => $this->onGetUom($value['uom_code']),
                'primary_item_packing_size' => $value['primary_item_packing_size'] == "" ? null : $value['primary_item_packing_size'],
                'secondary_item_packing_size' => $value['secondary_item_packing_size'] == "" ? null : $value['secondary_item_packing_size'],
                'primary_conversion_id' => $this->onGetPrimaryConversion($value['primary_conversion_code']),
                'secondary_conversion_id' => $this->onGetSecondaryConversion($value['secondary_conversion_code']),
                'sticker_remarks_code' => $value['sticker_remarks_code'],
                'is_viewable_by_otb' => $value['is_viewable_by_otb'] ?? 0
            ]);
        }
    }

    public function onGetParentId($value)
    {
        $item = ItemMasterdataModel::where('item_code', $value)->first();
        return $item->id ?? null;
    }

    public function onGetItemClassification($value)
    {
        return ItemClassificationModel::where('code', $value)->first()->id ?? null;
    }
    public function onGetItemCategory($value)
    {
        return ItemCategoryModel::where('code', $value)->first()->id ?? null;
    }
    public function onGetStorageType($value)
    {
        return StorageTypeModel::where('code', $value)->first()->id ?? null;
    }
    public function onGetItemVariantType($value)
    {
        return ItemVariantTypeModel::where('code', $value)->first()->id ?? null;
    }
    public function onGetPlant($value)
    {
        return FacilityPlantModel::where('code', $value)->first()->id ?? null;
    }
    public function onGetUom($value)
    {
        return ItemUomModel::where('code', $value)->first()->id ?? null;
    }
    public function onGetPrimaryConversion($value)
    {
        return ItemConversionModel::where('code', $value)->first()->id ?? null;
    }
    public function onGetSecondaryConversion($value)
    {
        return ItemConversionModel::where('code', $value)->first()->id ?? null;
    }
}
